algoritmo "semnome"
// Função :
// Autor :
// Data : 26/03/2019
// Seção de Declarações 
var
cm,m,dc,mm:real
inicio
// Seção de Comandos 
escreval("conversao de medida")
escreval("digite a quantidade de centímetros")
leia(cm)
mm<-cm*10
escreval("esse é o seu valor em milímetro",mm)
dc<-cm/10
escreval("esse é o seu valor em decímetro",dc)
m<-dc/10
escreval("esse é o seu valor em metros",m)






fimalgoritmo
