algoritmo "semnome"
// Função :
// Autor :
// Data : 26/03/2019
// Seção de Declarações 
var
a,b,c,x1,x2,x:real
inicio
// Seção de Comandos 
escreval("funçao 2° grau")
escreval("digite o valor de a")
leia(a)
escreval("digite o valor de b")
leia(b)
escreval("digite o valor de c")
leia(c)
x1<- (-b+ raizq (b^2-4*a*c))/2*a
escreval("o valor de x1é:",x1)
x2<- (-b- raizq  (b^2-4*a*c))/2*a
escreval("o valor de x1é:",x2)
fimalgoritmo
